### ISSUE TITLE
after core updated pokerbot not work

### ISSUE THREAD

**Issue by srwgin** [Frizz925/gbf-autopilot-poker#3]
it click fast than the table situation
for example
first round 
A A 2 5 6//it should keep A A but it not keep AA just change all card
second round
K A 1 4 5//it keep K A，it look like it keep card before this round

**Comment by srwgin** [comment]
this is the whole Iog I hope you can see something


D:\game\gbf\gbfbackup\gbf-autopilot>npm start

> gbf-autopilot@0.0.1 start D:\game\gbf\gbfbackup\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python controller.py"

[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] 2018-01-22T08:49:46.960Z - debug: Started listening on localhost:49544
[0] 2018-01-22T08:49:51.784Z - debug: Client 'LHgR3Mc-eT9fMlR4AAAA' connected!
[0] 2018-01-22T08:49:51.802Z - debug: Socket 'LHgR3Mc-eT9fMlR4AAAA' started
[1] 127.0.0.1 - - [22/Jan/2018 16:49:51] "POST /start HTTP/1.1" 200 -
[0] 2018-01-22T08:49:51.834Z - info: Autopilot started.
[0] 2018-01-22T08:49:51.838Z - info: Using 'Poker' mode.
[0] 2018-01-22T08:49:54.333Z - debug: Location change: #casino/list/poker
[0] 2018-01-22T08:49:55.344Z - debug: Waiting element: .atx-lead-link
[0] 2018-01-22T08:49:55.353Z - debug: Clicking with condition: .btn-game[game-id='200040']
[0] 2018-01-22T08:49:55.354Z - debug: Checking element: .pop-poker.pop-show
[0] 2018-01-22T08:49:55.382Z - debug: Clicking element: .btn-game[game-id='200040']
[1] 127.0.0.1 - - [22/Jan/2018 16:49:55] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:49:55.928Z - debug: Timeout: 750
[0] 2018-01-22T08:49:56.679Z - debug: Checking element: .pop-poker.pop-show
[0] 2018-01-22T08:49:56.686Z - debug: Clicking with condition: .btn-double.type1
[0] 2018-01-22T08:49:56.686Z - debug: Checking element: .pop-poker.pop-show
[0] 2018-01-22T08:49:56.691Z - debug: Clicking element: .btn-double.type1
[1] 127.0.0.1 - - [22/Jan/2018 16:49:57] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:49:57.185Z - debug: Timeout: 750
[0] 2018-01-22T08:49:57.936Z - debug: Checking element: .pop-poker.pop-show
[0] 2018-01-22T08:49:58.951Z - debug: Waiting element: .cnt-poker
[0] 2018-01-22T08:49:59.947Z - debug: Timeout: 1500
[0] 2018-01-22T08:50:01.447Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:01.454Z - debug: Clicking with condition: .prt-start
[0] 2018-01-22T08:50:01.454Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:01.463Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:01] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:01.969Z - debug: Timeout: 750
[0] 2018-01-22T08:50:02.719Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:02.726Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:03] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:03.271Z - debug: Timeout: 750
[0] 2018-01-22T08:50:04.021Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:04.040Z - debug: Checking element: .prt-low
[0] 2018-01-22T08:50:04.054Z - info: Playing poker
[0] 2018-01-22T08:50:04.054Z - debug: Waiting element: .prt-ok
[0] 2018-01-22T08:50:04.060Z - debug: Timeout: 500
[0] 2018-01-22T08:50:04.578Z - debug: From deal model
[0] 2018-01-22T08:50:04.584Z - debug: Suggestion: joker 0
[1] 127.0.0.1 - - [22/Jan/2018 16:50:05] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:05.096Z - debug: Clicking with condition: .prt-ok
[0] 2018-01-22T08:50:05.096Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:05.105Z - debug: Clicking element: .prt-ok
[1] 127.0.0.1 - - [22/Jan/2018 16:50:05] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:05.602Z - debug: Timeout: 750
[0] 2018-01-22T08:50:06.353Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:06.359Z - debug: Clicking element: .prt-ok
[1] 127.0.0.1 - - [22/Jan/2018 16:50:06] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:06.855Z - debug: Timeout: 750
[0] 2018-01-22T08:50:07.605Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:07.610Z - debug: Clicking element: .prt-ok
[1] 127.0.0.1 - - [22/Jan/2018 16:50:08] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:08.115Z - debug: Timeout: 750
[0] 2018-01-22T08:50:08.866Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:08.881Z - debug: Waiting element: .prt-start,.prt-yes
[0] 2018-01-22T08:50:08.887Z - debug: Checking element: .prt-yes
[0] 2018-01-22T08:50:08.902Z - debug: Clicking with condition: .prt-start
[0] 2018-01-22T08:50:08.902Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:08.911Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:09] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:09.408Z - debug: Timeout: 750
[0] 2018-01-22T08:50:10.159Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:10.165Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:10] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:10.688Z - debug: Timeout: 750
[0] 2018-01-22T08:50:11.440Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:11.445Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:11] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:11.950Z - debug: Timeout: 750
[0] 2018-01-22T08:50:12.702Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:12.717Z - info: Playing poker
[0] 2018-01-22T08:50:12.717Z - debug: Waiting element: .prt-ok
[0] 2018-01-22T08:50:12.726Z - debug: Timeout: 500
[0] 2018-01-22T08:50:13.231Z - debug: From deal model
[0] 2018-01-22T08:50:13.232Z - debug: Suggestion: onePair 0
[1] 127.0.0.1 - - [22/Jan/2018 16:50:13] "POST /click HTTP/1.1" 200 -
[1] 127.0.0.1 - - [22/Jan/2018 16:50:14] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:14.260Z - debug: Clicking with condition: .prt-ok
[0] 2018-01-22T08:50:14.260Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:14.266Z - debug: Clicking element: .prt-ok
[1] 127.0.0.1 - - [22/Jan/2018 16:50:14] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:14.798Z - debug: Timeout: 750
[0] 2018-01-22T08:50:15.548Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:15.563Z - debug: Waiting element: .prt-start,.prt-yes
[0] 2018-01-22T08:50:15.570Z - debug: Checking element: .prt-yes
[0] 2018-01-22T08:50:15.593Z - debug: Clicking with condition: .prt-start
[0] 2018-01-22T08:50:15.594Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:15.599Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:16] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:16.110Z - debug: Timeout: 750
[0] 2018-01-22T08:50:16.860Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:16.866Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:17] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:17.354Z - debug: Timeout: 750
[0] 2018-01-22T08:50:18.104Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:18.110Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:18] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:18.624Z - debug: Timeout: 750
[0] 2018-01-22T08:50:19.375Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:19.386Z - info: Playing poker
[0] 2018-01-22T08:50:19.387Z - debug: Waiting element: .prt-ok
[0] 2018-01-22T08:50:19.392Z - debug: Timeout: 500
[0] 2018-01-22T08:50:19.898Z - debug: From deal model
[0] 2018-01-22T08:50:19.899Z - debug: Suggestion: onePair 0
[1] 127.0.0.1 - - [22/Jan/2018 16:50:20] "POST /click HTTP/1.1" 200 -
[1] 127.0.0.1 - - [22/Jan/2018 16:50:20] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:20.914Z - debug: Clicking with condition: .prt-ok
[0] 2018-01-22T08:50:20.914Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:20.924Z - debug: Clicking element: .prt-ok
[1] 127.0.0.1 - - [22/Jan/2018 16:50:21] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:21.429Z - debug: Timeout: 750
[0] 2018-01-22T08:50:22.179Z - debug: Checking element: .prt-ok
[0] 2018-01-22T08:50:22.193Z - debug: Waiting element: .prt-start,.prt-yes
[0] 2018-01-22T08:50:22.206Z - debug: Checking element: .prt-yes
[0] 2018-01-22T08:50:22.224Z - debug: Clicking with condition: .prt-start
[0] 2018-01-22T08:50:22.225Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:22.229Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:22] "POST /click HTTP/1.1" 200 -
[0] 2018-01-22T08:50:22.724Z - debug: Timeout: 750
[0] 2018-01-22T08:50:23.475Z - debug: Checking element: .prt-start
[0] 2018-01-22T08:50:23.483Z - debug: Clicking element: .prt-start
[1] 127.0.0.1 - - [22/Jan/2018 16:50:23] "POST /click HTTP/1.1" 500 -
[0] 2018-01-22T08:50:23.500Z - info: AP potion used: 0
[0] 2018-01-22T08:50:23.500Z - error:  Error: Request failed with status code 500
[0]     at createError (D:\game\gbf\gbfbackup\gbf-autopilot\node_modules\axios\lib\core\createError.js:16:15)
[0]     at settle (D:\game\gbf\gbfbackup\gbf-autopilot\node_modules\axios\lib\core\settle.js:18:12)
[0]     at IncomingMessage.handleStreamEnd (D:\game\gbf\gbfbackup\gbf-autopilot\node_modules\axios\lib\adapters\http.js:191:11)
[0]     at emitNone (events.js:111:20)
[0]     at IncomingMessage.emit (events.js:208:7)
[0]     at endReadableNT (_stream_readable.js:1055:12)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0] 2018-01-22T08:50:23.501Z - debug: Stopping socket 'LHgR3Mc-eT9fMlR4AAAA'
[1] 127.0.0.1 - - [22/Jan/2018 16:50:23] "POST /stop HTTP/1.1" 200 -
[0] 2018-01-22T08:50:23.513Z - info: Autopilot stopped.
[0] 2018-01-22T08:50:24.261Z - debug: Got stop request from webhook
[0] 2018-01-22T08:50:24.261Z - debug: Autopilot is not running!

**Comment by Frizz925** [comment]
The error is thrown from the input controller. Usually this happens because the controller failed to find the window with matching name (eg: Granblue Fantasy - Google Chrome).

**Comment by srwgin** [comment]
[0] 2018-01-22T08:50:23.500Z - error: Error: Request failed with status code 500
this because I use F1 stop bot sametme open the chrome help page

**Comment by Frizz925** [comment]
The F1 key was supposed to be a failsafe key, causing both controller and main server to error and stop the bot immediately. It's kinda hacky but it works so far.
