### ISSUE TITLE
PokerMode can`t run

### ISSUE THREAD

**Issue by cccwzi** [Frizz925/gbf-autopilot-poker#5]
Summary
PokerMode can`t run

Branch
master

Commit hash
69a86f59965ecc892f2f41eeca5de8ffd7ab0502

Steps to reproduce
> gbf-autopilot@0.0.1 start D:\WEB\gbf\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python server.py"

[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] 2018-03-03T12:24:01.494Z - debug: Started listening on localhost:49544
[0] 2018-03-03T12:24:01.881Z - debug: Client 'CnTTWyyBeQK-J8r8AAAA' connected!
[0] 2018-03-03T12:24:12.766Z - debug: Socket 'CnTTWyyBeQK-J8r8AAAA' started
[1] 127.0.0.1 - - [03/Mar/2018 20:24:12] "POST / HTTP/1.1" 200 -
[0] 2018-03-03T12:24:12.780Z - info: Autopilot started.
[0] 2018-03-03T12:24:12.860Z - info: Waiting for supporter page...

> gbf-autopilot@0.0.1 test D:\WEB\gbf\gbf-autopilot
> npm run test:lib && npm run test:server && npm run test:controller

> gbf-autopilot@0.0.1 test:lib D:\WEB\gbf\gbf-autopilot
> mocha --require babel-register test/lib/**/*.js

  Config wrapper test
    √ should destructure dot keys

  1 passing (14ms)

> gbf-autopilot@0.0.1 test:server D:\WEB\gbf\gbf-autopilot
> mocha test/server/**/*.js

  Test server dry run
2018-03-03T12:25:38.406Z - debug: Started listening on localhost:49544
    √ should listen normally (988ms)

  1 passing (997ms)

> gbf-autopilot@0.0.1 test:controller D:\WEB\gbf\gbf-autopilot
> python -m nose test.controller

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Actual results
PokerMode can`t run

More Info
System information
OS: Windows 10 Pro 64-bit
Screen resolution: 2560x1440 @ 1.0x
Chrome version: 64.0.3282.186 (Official Build) (64-bit)
Node.js version: v8.9.4
Python version: 3.5.2

Configuration
[Server]
ListenerPort=49544
ProcessTimeoutInMs=60000
WorkerTimeoutInMs=500
WaitAjaxTimeoutInMs=5000
JsonRpcEndpoint=/jsonrpc

[Controller]
ListenerPort=49545
MouseTween=easeInOutCubic

[Debug]
LogLevel=debug
LogToFile=false
LogToOutput=true
LogToFileDirectory=log
LogSocket=false
ThrowErrors=false
TrialBattleMode=false

[General]
Language=en
MaxNumActionRetries=3
MinWaitTimeInMsAfterRefresh=2000
TimeLimitInSeconds=3600
UseViramate=true
MaxNumPotionsToUse=999
UseFullElixirsWhenNoRemainingHalfAPPotions=false
UseFullElixirsFirst=false
TreasureId=
TreasureName=
TreasureTarget=

[Inputs]
DelayInMsBetweenMouseDownAndUp=40
RandomDelayInMsBetweenMouseDownAndUp=20
MouseSpeed=580
MouseSpeedBase=150
MouseScrollSpeed=250
ExitKeyCode=112
WaitTimeInMsBeforeClickInput=50

[PartySelection]
PreferredPartyGroup=1
PreferredPartyDeck=5
PreferredPartySet=A
PreferredNightmareModePartyGroup=1
PreferredNightmareModePartyDeck=1
PreferredNightmareModePartySet=A

[Summons]
PreferredSummons=Kaguya,Rabbit
DefaultSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFound=false

[Combat]
MinWaitTimeInMsAfterAttack=500
MinWaitTimeInMsAfterSummon=3000
MinWaitTimeInMsAfterAbility=2200
LuaScript=

[PokerMode]
Enabled=true
ChipAmount=1000
WinningRoundCap=5
WinningChipsCap=16000
WinningRateBase=0.75
WinningRateModifier=0.08

[EventMode]
Enabled=false
EventRaidUrl="http://game.granbluefantasy.jp/#quest/supporter/510031/5"
EventRaidScript=
NightmareModeUrl="http://game.granbluefantasy.jp/#quest/supporter/510051/5"
NightmareModeScript=
EventPageUrl="http://game.granbluefantasy.jp/#quest/extra"
NightmareModePreferredSummons=Kaguya
NightmareModeSummonAttributeTab=Mise
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false
WaitTimeInMsAfterEventPageIsLoaded=1000

[EventTreasureMode]
Enabled=false
EventTreasureUrl=
EventTreasureSoloUrl=
EventTreasureSoloModeScript=
EventTreasureRaidUrl=
EventTreasureRaidModeScript=
EventTreasureRaidItemRequiredCount=
NightmareModeUrl=
NightmareModeScript=
NightmareModePreferredSummons=
NightmareModeSummonAttributeTab=
RerollSummonWhenNoPreferredSummonWasFoundForNightmareMode=true
NightmareModeAvailableAtStart=false

[RiseOfTheBeastsMode]
Enabled=false
RiseOfTheBeastsUrl=
RiseOfTheBeastsLuaScript=

[CoopSoloMode]
Enabled=false
LuaScript=

[CoopGuestMode]
Enabled=false
LuaScript=

[CustomizedScheduling]
Enabled=false
SchedulingLuaScript=

[DimensionalHalo]
RetreatWhenNoDimensionalHaloTransformation=true

**Comment by Frizz925** [comment]
Have you created the extensions.js file?

**Comment by cccwzi** [comment]
OH I forgot!
But I got new error when i added it(The test is OK).

> gbf-autopilot@0.0.1 start D:\WEB\gbf\gbf-autopilot
> cross-env NODE_ENV=production concurrently "node index.js" "python server.py"

[1]  * Running on http://localhost:49545/ (Press CTRL+C to quit)
[0] 2018-03-04T09:38:05.061Z - debug: Started listening on localhost:49544
[0] 2018-03-04T09:38:06.867Z - debug: Client 'qRwMv83jag11-vSPAAAA' connected!
[0] 2018-03-04T09:38:12.464Z - debug: Socket 'qRwMv83jag11-vSPAAAA' started
[1] 127.0.0.1 - - [04/Mar/2018 17:38:12] "POST / HTTP/1.1" 200 -
[0] 2018-03-04T09:38:12.477Z - info: Autopilot started.
[0] 2018-03-04T09:38:12.479Z - info: AP potion used: 0
[0] 2018-03-04T09:38:12.479Z - error:  TypeError: Cannot read property 'Enabled' of undefined
[0]     at Function.exports.test (D:\WEB\gbf\gbf-autopilot\node_modules\gbf-autopilot-poker\src\PokerPipeline.js:23:45)
[0]     at WorkerContainer.inject (D:\WEB\gbf\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\worker\workerContainer.js:38:21)
[0]     at D:\WEB\gbf\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\worker\events\onBeforeStart.js:25:30
[0]     at arrayEach (D:\WEB\gbf\gbf-autopilot\node_modules\lodash\_arrayEach.js:15:9)
[0]     at forEach (D:\WEB\gbf\gbf-autopilot\node_modules\lodash\forEach.js:38:10)
[0]     at SafeSubscriber.onBeforeStart [as _next] (D:\WEB\gbf\gbf-autopilot\node_modules\gbf-autopilot-core\build\server\worker\events\onBeforeStart.js:19:27)
[0]     at SafeSubscriber.__tryOrUnsub (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:239:16)
[0]     at SafeSubscriber.next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:186:22)
[0]     at Subscriber._next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:126:26)
[0]     at Subscriber.next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:90:18)
[0]     at MapSubscriber._next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\operators\map.js:85:26)
[0]     at MapSubscriber.Subscriber.next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:90:18)
[0]     at FilterSubscriber._next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\operators\filter.js:89:30)
[0]     at FilterSubscriber.Subscriber.next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:90:18)
[0]     at MapSubscriber._next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\operators\map.js:85:26)
[0]     at MapSubscriber.Subscriber.next (D:\WEB\gbf\gbf-autopilot\node_modules\rxjs\Subscriber.js:90:18)
[0] 2018-03-04T09:38:12.479Z - info: BP berry used: 0
[0] 2018-03-04T09:38:12.479Z - debug: Stopping socket 'qRwMv83jag11-vSPAAAA'
[1] 127.0.0.1 - - [04/Mar/2018 17:38:12] "POST / HTTP/1.1" 200 -
[0] 2018-03-04T09:38:12.483Z - info: Autopilot stopped.

**Comment by Frizz925** [comment]
Oh yeah, the Poker extension isn't forward compatible with the new configuration parser. Gonna fix it real quick.

**Comment by Frizz925** [comment]
https://github.com/Frizz925/gbf-autopilot-poker/commit/c5c9af84ad6d57001e9b0a8c7cf79c5762237cab Should hopefully fix it.
